//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessAcessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ChamCong
    {
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public Nullable<int> SoBuoiLam { get; set; }
        public Nullable<int> SoBuoiNghi { get; set; }
        public Nullable<double> Luong { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
    }
}
